version: '3.7'

services:
  log4j:
    build: .
    ports:
      - '80:8080'
    volumes:
      - './log.json:/honeypot/log.json'
      - './payloads.json:/honeypot/payloads'
    restart: unless-stopped
